#!/bin/bash

set -o errexit
set -o nounset


worker_ready(){
    celery -A story_api inspect ping
}

until worker_ready; do
    >&2 echo "Celery workers are not available :-("
    sleep 1
done
>&2 echo "Celery workers are available and ready!....:-)"

exec watchfiles celery.__main__.main \
--args \
"-A story_api.celery -b \"${CELERY_BROKER}\" flower --basic-auth=\"${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}\""